name: Trigger auto deployment for container-app-3d5rsqc3u7u6e

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-3d5rsqc3u7u6e-AutoDeployTrigger-877dbc00-5da7-4f41-aa6f-18c1a523f199.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3D5RSQC3U7U6E_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3D5RSQC3U7U6E_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3D5RSQC3U7U6E_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3D5RSQC3U7U6E_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3D5RSQC3U7U6E_REGISTRY_PASSWORD }}
          containerAppName: container-app-3d5rsqc3u7u6e
          resourceGroup: todonodejspgsqlgoogleauthacd2bede
          imageToBuild: default/[parameters('containerAppNamebackend')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


